# Generated by Django 5.2.1 on 2025-07-29 23:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklysummary',
            unique_together={('user', 'week_start', 'week_end')},
        ),
    ]
