# Generated by Django 5.2.1 on 2026-03-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_alter_dailysummary_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='daily_summaries/photos/'),
        ),
    ]
