# Generated by Django 5.2.1 on 2026-03-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0003_dailysummary_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='weeklysummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_summaries/photos/'),
        ),
    ]
