# Generated by Django 5.2.1 on 2026-04-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0004_alter_dailysummary_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='is_processed_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='suggested_topics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
