# Generated by Django 5.2.1 on 2026-04-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0005_dailysummary_ai_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='is_processed_by_ai',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
