# Generated by Django 5.2.1 on 2026-06-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0006_alter_dailysummary_is_processed_by_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='category',
            field=models.CharField(default='Outros', max_length=100),
        ),
    ]
